### ISSUE TITLE
compartir siembra fertilizada no indica los kg de fertilizante y no muestra codigo qr

### ISSUE THREAD

**Issue by kotogadekiru** [kotogadekiru/UrsulaGIS#15]
Al generar una siembra fertilizada y compartir nos muestra el formulario con los datos del contratista y etc. pero en la lista de materiales solo incluye la semilla y no el fertilizante.

**Comment by kotogadekiru** [comment]
esto sucede el 5/11/2023 en la version de desarrollo 0.2.29 commit b078b5a313ff95318b7d45b2f0bffd79abde8ef2

**Comment by JuaniElias** [comment]
No puedo reproducir a commit 7a24c824ec0da15d102a4205670754497d97d4f4. Se Muestra los fertilizantes y sale el QR.
Lo que si se muestran duplicados:
![image](https://github.com/kotogadekiru/UrsulaGIS-Desktop/assets/59778404/e001ba70-c1e1-4583-a410-b0bb81b5cd23)
Con #22 se evita el error de crearlas sin que esten seleccionadas alguna de las 2 ordenes
